/**
 * Downloads the two reference corpora and normalizes them to Ingot's schema.
 *
 *   human   databricks-dolly-15k   written by Databricks employees   CC-BY-SA-3.0
 *   machine stanford alpaca 52k    generated by text-davinci-003     CC-BY-NC-4.0
 *
 * Both are chosen because their provenance is stated by their own authors, which
 * is the only honest way to calibrate a provenance scanner. Alpaca is
 * non-commercial licensed: fine for calibration and research, stated in the report.
 *
 * Fairness filters, applied identically to both so the comparison is not rigged:
 *   - only prompts with no attached source passage, so no response can copy from
 *     context and inflate the duplicate signal
 *   - at least 10 words, so sentence-level statistics exist
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const DOLLY_URL =
  'https://huggingface.co/datasets/databricks/databricks-dolly-15k/resolve/main/databricks-dolly-15k.jsonl';
const ALPACA_URL = 'https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json';

const OPEN_ENDED_DOLLY = new Set(['brainstorming', 'creative_writing', 'open_qa', 'general_qa']);
const MIN_WORDS = 10;

type Out = { id: string; text: string; prompt: string; source: string };

function wordCount(s: string): number {
  return (s.trim().match(/\S+/g) ?? []).length;
}

async function get(url: string): Promise<string> {
  process.stdout.write(`  fetching ${url}\n`);
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return await res.text();
}

async function dolly(): Promise<Out[]> {
  const raw = await get(DOLLY_URL);
  const out: Out[] = [];
  let i = 0;
  for (const line of raw.split('\n')) {
    const t = line.trim();
    if (!t) continue;
    let row: Record<string, unknown>;
    try {
      row = JSON.parse(t) as Record<string, unknown>;
    } catch {
      continue;
    }
    const category = String(row.category ?? '');
    const context = String(row.context ?? '');
    const response = String(row.response ?? '');
    const instruction = String(row.instruction ?? '');
    if (!OPEN_ENDED_DOLLY.has(category)) continue;
    if (context.trim().length > 0) continue;
    if (wordCount(response) < MIN_WORDS) continue;
    out.push({ id: `dolly-${++i}`, text: response, prompt: instruction, source: `dolly:${category}` });
  }
  return out;
}

async function alpaca(): Promise<Out[]> {
  const raw = await get(ALPACA_URL);
  const rows = JSON.parse(raw) as { instruction?: string; input?: string; output?: string }[];
  const out: Out[] = [];
  let i = 0;
  for (const row of rows) {
    const input = String(row.input ?? '');
    const output = String(row.output ?? '');
    if (input.trim().length > 0) continue;
    if (wordCount(output) < MIN_WORDS) continue;
    out.push({ id: `alpaca-${++i}`, text: output, prompt: String(row.instruction ?? ''), source: 'alpaca:davinci-003' });
  }
  return out;
}

function writeJsonl(path: string, rows: Out[]): void {
  mkdirSync(resolve('data'), { recursive: true });
  writeFileSync(path, rows.map((r) => JSON.stringify(r)).join('\n') + '\n', 'utf8');
  process.stdout.write(`  wrote ${rows.length.toLocaleString()} records → ${path}\n`);
}

const [human, machine] = await Promise.all([dolly(), alpaca()]);
writeJsonl(resolve('data/human-dolly.jsonl'), human);
writeJsonl(resolve('data/machine-alpaca.jsonl'), machine);
process.stdout.write('\n  next: node scripts/build-baselines.ts\n\n');
